package Selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.junit.jupiter.api.Assertions;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import java.time.Duration;
import java.util.*;
public class RatingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void rating() {
    driver.get("http://localhost:3000/");
    driver.findElement(By.cssSelector(".Choices:nth-child(1)")).click();
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
    wait.until(ExpectedConditions.alertIsPresent());
    if(driver.switchTo().alert().getText().equals("Player 2 wins player 1\'s card"))
    {
      Assertions.assertEquals(driver.switchTo().alert().getText(), "Player 2 wins player 1\'s card", "Alert isn't showing the correct result");
    }
    else
    {
      Assertions.assertEquals(driver.switchTo().alert().getText(), "Player 1 wins player 2\'s card", "Alert isn't showing the correct result");
    }
  }
}
